language: c++

addons:
  apt:
    packages:
      - libboost-all-dev

compiler:
  - clang

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - make test
